Import( 'project', 'libs' )

project.ObjectLibrary(
		'comparator',
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.specReader,
			libs.fileReader,
			libs.basicelement,
			libs.report,
			],
	)
