Import( 'project', 'libs' )

project.StaticLibrary(
		'comparator',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.fileReader,
			libs.elementChecker,
			libs.report,
			],
		shared = True
	)

project.pySwigBinding(
		packageName = "pyFileMetaChecker",
		moduleName  = "comparator",
		sources     = [ 'src/Comparator/Comparator.i' ],
		libraries   = [ libs.comparator ],
	)
