Import( 'project', 'libs' )

project.StaticLibrary(
		'comparator',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.fileReader,
			libs.elementChecker,
			libs.reportGenerator,
			],
		shared = True
	)


