Import( 'project', 'libs' )

project.StaticLibrary(
	'extractor',
	dirs      = ['src'],
	includes  = ['src'],
	libraries = [
		libs.boost_filesystem,
		libs.common,
		libs.report,
		libs.boost_python,
		],
	shared = True
)
