Import( 'project', 'libs' )

project.Program(
		target='main',
		sources=['main.cpp'],
		libraries = [
			libs.boost,
			libs.fileReader,
			libs.specReader,
			libs.reportGenerator,
			libs.comparator,
			],
	)


