Import( 'project', 'libs' )

project.StaticLibrary(
		'fileReader',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [ ],
		shared = True
	)

project.pySwigBinding(
		packageName = "pyFileMetaChecker",
		moduleName  = "fileReader",
		sources     = [ 'src/FileReader/FileReader.i' ],
		libraries   = [ libs.fileReader ],
	)
