Import( 'project', 'libs' )

project.UnitTest(
	target = "TestSpecification",
	dirs = ['Specification'],
	libraries = [
		libs.specReader,
		libs.boost_unit_test_framework,
	]
)

project.UnitTest(
	target = "TestExpressionParser",
	dirs = ['ExpressionParser'],
	libraries = [
		libs.specReader,
		libs.boost_unit_test_framework,
	]
)

