Import( 'project', 'libs' )

project.StaticLibrary(
		'basicElement',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.specReader,
		],
		shared = True
	)

project.pySwigBinding(
		packageName = "pyFileMetaChecker",
		moduleName  = "element",
		sources     = [ 'src/BasicElement/Element.i' ],
		libraries   = [ libs.basicElement ],
	)
