Import( 'project', 'libs' )

project.StaticLibrary(
		'basicelement',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.boost_python,
			libs.specReader,
			],
		shared = True
	)
