Import( 'project', 'libs' )

project.ObjectLibrary(
		'basicelement',
		includes=[project.getRealAbsoluteCwd('src')],
		libraries = [
			libs.common,
			libs.boost_python,
			libs.specReader,
			],
	)
