Import( 'project', 'libs' )

project.UnitTest(
	target = "TestReportGenerator",
	sources = ['reportGeneratorTest.cpp'],
	libraries = [
		libs.reportGenerator,
		libs.boost_unit_test_framework,
	]
)


