Import( 'project', 'libs' )

project.UnitTest(
	target = "TestBasicElement",
	sources = ['elementTest.cpp'],
	# dirs = ['.'],
	libraries = [
		libs.basicElement,
		libs.boost_unit_test_framework,
	]
)
