Import( 'project', 'libs' )

qc = project.Program(
	target='fileMetaChecker',
	dirs=['FileMetaChecker'],
	includes=['FileMetaChecker'],
	libraries = [
		libs.boost_filesystem,
		libs.boost_program_options,
		libs.common,
		libs.fileReader,
		libs.specReader,
		libs.report,
		libs.comparator,
	]
)

specChecker = project.Program(
	target='specChecker',
	dirs=['SpecChecker'],
	includes=['SpecChecker'],
	libraries = [
		libs.boost_filesystem,
		libs.boost_program_options,
		libs.common,
		libs.specReader,
	]
)

