Import( 'project', 'libs' )

project.StaticLibrary(
		'elementChecker',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.boost_python,
			libs.basicElement,
		],
		shared = True
	)


