Import( 'project', 'libs' )

project.StaticLibrary(
		'specReader',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.common,
			libs.rapidparser,
			libs.boost,
			libs.boost_filesystem,
		],
		shared = True
	)

project.pySwigBinding(
		packageName = "pyFileMetaChecker",
		moduleName  = "specReader",
		sources     = [ 'src/SpecReader/Spec.i' ],
		libraries   = [ libs.specReader ],
	)
