Import( 'project', 'libs' )

project.StaticLibrary(
		'report',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.rapidxml,
			libs.common,
			libs.basicElement,
			],
		shared = True
	)

project.pySwigBinding(
		packageName = "pyFileMetaChecker",
		moduleName  = "report",
		sources     = [ 'src/Report/Report.i' ],
		libraries   = [ libs.report ],
	)
