Import( 'project', 'libs' )

project.StaticLibrary(
		'report',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.boost,
			libs.common,
			libs.basicelement,
			],
		shared = True
	)
