Import( 'project', 'libs' )

project.StaticLibrary(
		'common',
		dirs      = ['src'],
		includes  = ['src'],
		libraries = [
			libs.boost_system,
			libs.boost_log,
			libs.boost_thread,
		],
		shared = True
	)
